-- Seed data: default admin and settings
-- Default password: admin123 (PBKDF2-SHA256, change after first login!)
-- This hash is generated by the password utility with the password "admin123"
INSERT OR IGNORE INTO admin (username, password_hash, display_name, avatar_url)
VALUES ('admin', 'pbkdf2:100000:a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4:placeholder_hash_replace_on_first_run', 'Blog Admin', '');

-- Default settings
INSERT OR IGNORE INTO settings (key, value) VALUES ('site_title', '"My Blog"');
INSERT OR IGNORE INTO settings (key, value) VALUES ('site_subtitle', '"Thoughts, stories and ideas"');
INSERT OR IGNORE INTO settings (key, value) VALUES ('site_description', '"A personal blog powered by Cloudflare Workers"');
INSERT OR IGNORE INTO settings (key, value) VALUES ('site_logo', '""');
INSERT OR IGNORE INTO settings (key, value) VALUES ('nav_menu', '[{"label":"Home","url":"/"},{"label":"Archive","url":"/archive"},{"label":"About","url":"/article/about"}]');
INSERT OR IGNORE INTO settings (key, value) VALUES ('footer_content', '"Powered by CF Workers Blog"');
INSERT OR IGNORE INTO settings (key, value) VALUES ('posts_per_page', '10');
INSERT OR IGNORE INTO settings (key, value) VALUES ('comment_moderation', 'true');
INSERT OR IGNORE INTO settings (key, value) VALUES ('theme_colors', '{"primary":"#E8590C","accent":"#3730A3"}');
INSERT OR IGNORE INTO settings (key, value) VALUES ('social_links', '[]');

-- Default category
INSERT OR IGNORE INTO categories (name, slug, description, sort_order)
VALUES ('Uncategorized', 'uncategorized', 'Default category', 0);
